# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: manage-incidents

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  region: eu-central-1
  profile: private

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "lambda:InvokeAsync"
#        - "lambda:InvokeFunction"
#      Resource: 
#        - "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - node_modules/**
  exclude:
    - package.json

functions:

  manageincidents:
    handler: index.manageincident
    events:
      - http:
          path: dynamo/manageincident
          method: post
          cors: true

